Repository team-urbanlife/back-end, pull requests merged in 2024-09, with the labels that each got.

#3 [Setting] SecurityConfig 설정
  src/main/java/com/wegotoo/config/SecurityConfig.java
Labels: ⚙ Setting

#7 [Deploy] 빌드 자동화 설정
  .github/workflows/wegotoo_dev.yml
  .github/workflows/wegotoo_prod.yml
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.dev.yml
  docker-compose.prod.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🌏 Deploy

#14 [Feature] Schedule 삭제 API 구현
  src/main/java/com/wegotoo/api/schedule/DetailedPlanController.java
  src/main/java/com/wegotoo/api/schedule/ScheduleController.java
  src/main/java/com/wegotoo/application/schedule/DetailedPlanService.java
  src/main/java/com/wegotoo/application/schedule/ScheduleService.java
  src/main/java/com/wegotoo/domain/schedule/repository/MemoRepository.java
  src/main/java/com/wegotoo/domain/schedule/repository/ScheduleDetailsRepository.java
  src/main/java/com/wegotoo/domain/schedule/repository/ScheduleGroupRepository.java
  src/test/java/com/wegotoo/api/schedule/DetailedPlanControllerTest.java
  src/test/java/com/wegotoo/api/schedule/ScheduleControllerTest.java
  src/test/java/com/wegotoo/application/schedule/DetailedPlanServiceTest.java
  src/test/java/com/wegotoo/application/schedule/ScheduleServiceTest.java
Labels: ✨ Feature

#13 [Feature] 카카오 소셜 로그인 구현
  .github/workflows/wegotoo_dev.yml
  .github/workflows/wegotoo_prod.yml
  .gitignore
  build.gradle
  src/main/java/com/wegotoo/config/SecurityConfig.java
  src/main/java/com/wegotoo/config/WebConfig.java
  src/main/java/com/wegotoo/domain/user/Role.java
  src/main/java/com/wegotoo/domain/user/User.java
  src/main/java/com/wegotoo/domain/user/repository/UserRepository.java
  src/main/java/com/wegotoo/infra/security/jwt/factory/JwtTokenFactory.java
  src/main/java/com/wegotoo/infra/security/jwt/provider/JwtTokenProvider.java
  src/main/java/com/wegotoo/infra/security/jwt/provider/SecretKeyProvider.java
  src/main/java/com/wegotoo/infra/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/wegotoo/infra/security/oauth/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/wegotoo/infra/security/oauth/handler/OAuth2FailureHandler.java
  src/main/java/com/wegotoo/infra/security/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/wegotoo/infra/security/user/CustomOAuth2User.java
  src/main/java/com/wegotoo/infra/security/user/OAuthAttribute.java
  src/main/java/com/wegotoo/infra/security/util/CookieUtils.java
  src/main/resources/application.yml
Labels: ✨ Feature

#16 [Refactor] DetailedPlan 순서 변경을 Drag & Drop 방식으로 동작하도록 변경
  src/main/java/com/wegotoo/api/schedule/DetailedPlanController.java
  src/main/java/com/wegotoo/api/schedule/request/DetailedPlanMoveRequest.java
  src/main/java/com/wegotoo/application/schedule/DetailedPlanService.java
  src/main/java/com/wegotoo/application/schedule/request/MovePlanRequest.java
  src/test/java/com/wegotoo/api/schedule/DetailedPlanControllerTest.java
  src/test/java/com/wegotoo/application/schedule/DetailedPlanServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#19 [Feature] Schedule 조회 API 구현
  src/main/java/com/wegotoo/api/schedule/ScheduleController.java
  src/main/java/com/wegotoo/api/schedule/ScheduleDetailsController.java
  src/main/java/com/wegotoo/application/OffsetLimit.java
  src/main/java/com/wegotoo/application/SliceResponse.java
  src/main/java/com/wegotoo/application/schedule/DetailedPlanService.java
  src/main/java/com/wegotoo/application/schedule/ScheduleDetailsService.java
  src/main/java/com/wegotoo/application/schedule/ScheduleService.java
  src/main/java/com/wegotoo/application/schedule/response/ScheduleFindAllResponse.java
  src/main/java/com/wegotoo/application/schedule/response/TravelPlanResponse.java
  src/main/java/com/wegotoo/domain/schedule/repository/DetailPlanRepository.java
  src/main/java/com/wegotoo/domain/schedule/repository/DetailPlanRepositoryCustom.java
  src/main/java/com/wegotoo/domain/schedule/repository/DetailPlanRepositoryImpl.java
  src/main/java/com/wegotoo/domain/schedule/repository/ScheduleDetailsRepository.java
  src/main/java/com/wegotoo/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/wegotoo/domain/schedule/repository/querydsl/DetailPlanRepositoryCustom.java
  src/main/java/com/wegotoo/domain/schedule/repository/querydsl/DetailPlanRepositoryImpl.java
  src/main/java/com/wegotoo/domain/schedule/repository/querydsl/ScheduleDetailsRepositoryCustom.java
  src/main/java/com/wegotoo/domain/schedule/repository/querydsl/ScheduleDetailsRepositoryImpl.java
  src/main/java/com/wegotoo/domain/schedule/repository/querydsl/ScheduleRepositoryCustom.java
  src/main/java/com/wegotoo/domain/schedule/repository/querydsl/ScheduleRepositoryImpl.java
  src/main/java/com/wegotoo/domain/schedule/repository/response/DetailedPlanQueryEntity.java
  src/main/java/com/wegotoo/domain/schedule/repository/response/ScheduleDetailsQueryEntity.java
  src/main/java/com/wegotoo/domain/schedule/repository/response/ScheduleQueryEntity.java
  src/test/java/com/wegotoo/api/schedule/ScheduleControllerTest.java
  src/test/java/com/wegotoo/api/schedule/ScheduleDetailsControllerTest.java
  src/test/java/com/wegotoo/application/schedule/ScheduleDetailsServiceTest.java
  src/test/java/com/wegotoo/application/schedule/ScheduleServiceTest.java
  src/test/java/com/wegotoo/domain/schedule/repository/DetailPlanRepositoryImplTest.java
  src/test/java/com/wegotoo/domain/schedule/repository/querydsl/ScheduleDetailsRepositoryImplTest.java
  src/test/java/com/wegotoo/domain/schedule/repository/querydsl/ScheduleRepositoryImplTest.java
Labels: ✨ Feature

#22 [Docs] 일정 관리 API REST Docs 작성
  build.gradle
  src/docs/asciidoc/api/schedule/detailedPlan.adoc
  src/docs/asciidoc/api/schedule/schedule.adoc
  src/docs/asciidoc/api/schedule/scheduleDetails.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wegotoo/api/schedule/DetailedPlanController.java
  src/main/java/com/wegotoo/api/schedule/MemoController.java
  src/main/java/com/wegotoo/api/schedule/ScheduleController.java
  src/main/java/com/wegotoo/api/schedule/ScheduleDetailsController.java
  src/main/java/com/wegotoo/application/schedule/response/ScheduleFindAllResponse.java
  src/main/java/com/wegotoo/config/SecurityConfig.java
  src/main/java/com/wegotoo/domain/schedule/repository/response/DetailedPlanQueryEntity.java
  src/test/java/com/wegotoo/api/schedule/DetailedPlanControllerTest.java
  src/test/java/com/wegotoo/api/schedule/MemoControllerTest.java
  src/test/java/com/wegotoo/api/schedule/ScheduleControllerTest.java
  src/test/java/com/wegotoo/api/schedule/ScheduleDetailsControllerTest.java
  src/test/java/com/wegotoo/docs/RestDocsSupport.java
  src/test/java/com/wegotoo/docs/schedule/DetailedPlanControllerDocs.java
  src/test/java/com/wegotoo/docs/schedule/ScheduleControllerDocs.java
  src/test/java/com/wegotoo/docs/schedule/ScheduleDetailsControllerDocs.java
  src/test/java/com/wegotoo/support/security/TestSecurityContextFactory.java
  src/test/java/com/wegotoo/support/security/WithAuthUser.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/respnse-fields.snippet
Labels: 📃 Docs

#27 [Refactor] 채팅방 생성 API 기능 수정
  src/main/java/com/wegotoo/application/chatroom/ChatRoomService.java
  src/main/java/com/wegotoo/domain/chatroom/repository/ChatRoomRepository.java
  src/test/java/com/wegotoo/application/chatroom/ChatRoomServiceTest.java
Labels: 🔨 Refactor

#28 [Feature] Memo API 구현
  src/docs/asciidoc/api/schedule/memo.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wegotoo/api/schedule/MemoController.java
  src/main/java/com/wegotoo/api/schedule/request/MemoEditRequest.java
  src/main/java/com/wegotoo/api/schedule/request/MemoEditServiceRequest.java
  src/main/java/com/wegotoo/application/schedule/MemoService.java
  src/main/java/com/wegotoo/domain/schedule/Memo.java
  src/main/java/com/wegotoo/domain/schedule/repository/querydsl/DetailPlanRepositoryImpl.java
  src/main/java/com/wegotoo/domain/schedule/repository/response/DetailedPlanQueryEntity.java
  src/main/java/com/wegotoo/exception/ErrorCode.java
  src/test/java/com/wegotoo/api/schedule/MemoControllerTest.java
  src/test/java/com/wegotoo/application/schedule/MemoServiceTest.java
  src/test/java/com/wegotoo/docs/schedule/MemoControllerDocs.java
  src/test/java/com/wegotoo/docs/schedule/ScheduleDetailsControllerDocs.java
  src/test/java/com/wegotoo/domain/schedule/repository/DetailPlanRepositoryImplTest.java
Labels: ✨ Feature

#30 [Feature] 여행 모집글 생성 API 구현
  src/main/java/com/wegotoo/api/accompany/AccompanyController.java
  src/main/java/com/wegotoo/api/accompany/request/AccompanyCreateRequest.java
  src/main/java/com/wegotoo/application/accompany/AccompanyService.java
  src/main/java/com/wegotoo/application/accompany/request/AccompanyCreateServiceRequest.java
  src/main/java/com/wegotoo/domain/accompany/Accompany.java
  src/main/java/com/wegotoo/domain/accompany/Gender.java
  src/test/java/com/wegotoo/api/ControllerTestSupport.java
  src/test/java/com/wegotoo/api/accompany/AccompanyControllerTest.java
  src/test/java/com/wegotoo/application/accompany/AccompanyServiceTest.java
  src/test/java/com/wegotoo/docs/RestDocsSupport.java
  src/test/java/com/wegotoo/support/ControllerWebMvcTest.java
Labels: ✨ Feature

#35 [Feature] 여행 동행 게시글 삭제 API 구현
  src/main/java/com/wegotoo/api/accompany/AccompanyController.java
  src/main/java/com/wegotoo/application/accompany/AccompanyService.java
  src/test/java/com/wegotoo/api/accompany/AccompanyControllerTest.java
  src/test/java/com/wegotoo/application/accompany/AccompanyServiceTest.java
Labels: ✨ Feature

#37 [Feature] 여행 동행 게시글 조회 API 구현
  src/main/java/com/wegotoo/api/accompany/AccompanyController.java
  src/main/java/com/wegotoo/application/accompany/AccompanyService.java
  src/main/java/com/wegotoo/application/accompany/request/AccompanyCreateServiceRequest.java
  src/main/java/com/wegotoo/application/accompany/response/AccompanyFindAllResponse.java
  src/main/java/com/wegotoo/application/accompany/response/AccompanyFindOneResponse.java
  src/main/java/com/wegotoo/domain/accompany/Accompany.java
  src/main/java/com/wegotoo/domain/accompany/repository/AccompanyRepository.java
  src/main/java/com/wegotoo/domain/accompany/repository/AccompanyRepositoryCustom.java
  src/main/java/com/wegotoo/domain/accompany/repository/AccompanyRepositoryImpl.java
  src/main/java/com/wegotoo/domain/accompany/repository/response/AccompanyFindAllQueryEntity.java
  src/main/java/com/wegotoo/domain/accompany/repository/response/AccompanyFindOneQueryEntity.java
  src/test/java/com/wegotoo/api/accompany/AccompanyControllerTest.java
  src/test/java/com/wegotoo/application/accompany/AccompanyServiceTest.java
  src/test/java/com/wegotoo/domain/accompany/repository/AccompanyRepositoryImplTest.java
Labels: ✨ Feature

#40 [Feature] 로그 추적기 생성
  src/main/java/com/wegotoo/WegotooApplication.java
  src/main/java/com/wegotoo/config/SecurityConfig.java
  src/main/java/com/wegotoo/trace/LogTraceAspect.java
  src/main/java/com/wegotoo/trace/TraceId.java
  src/main/java/com/wegotoo/trace/TraceStatus.java
  src/main/java/com/wegotoo/trace/logtrace/LogTrace.java
  src/main/java/com/wegotoo/trace/logtrace/ThreadLocalLogTrace.java
Labels: ✨ Feature

#43 [Feature] 여행 도시 관련 API 구현
  src/docs/asciidoc/api/city/city.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wegotoo/api/city/CityController.java
  src/main/java/com/wegotoo/application/city/CityService.java
  src/main/java/com/wegotoo/application/city/response/CityResponse.java
  src/main/java/com/wegotoo/domain/city/City.java
  src/main/java/com/wegotoo/domain/city/District.java
  src/main/java/com/wegotoo/domain/city/Type.java
  src/main/java/com/wegotoo/domain/city/repository/CityRepository.java
  src/test/java/com/wegotoo/api/ControllerTestSupport.java
  src/test/java/com/wegotoo/docs/RestDocsSupport.java
  src/test/java/com/wegotoo/docs/city/CityControllerDocs.java
  src/test/java/com/wegotoo/support/ControllerWebMvcTest.java
Labels: ✨ Feature

#46 [Refactor] 동행 모집 글 리턴 데이터 변경
  src/main/java/com/wegotoo/api/accompany/AccompanyController.java
  src/main/java/com/wegotoo/application/accompany/AccompanyService.java
  src/main/java/com/wegotoo/application/accompany/response/AccompanyFindOneResponse.java
  src/main/java/com/wegotoo/domain/accompany/repository/AccompanyRepositoryImpl.java
  src/main/java/com/wegotoo/domain/accompany/repository/response/AccompanyFindOneQueryEntity.java
  src/test/java/com/wegotoo/docs/accompany/AccompanyControllerDocs.java
Labels: 🔨 Refactor

#47 [Refactor] Schedule API 리턴 데이터 변경
  src/main/java/com/wegotoo/api/schedule/ScheduleController.java
  src/main/java/com/wegotoo/application/schedule/ScheduleService.java
  src/test/java/com/wegotoo/docs/schedule/ScheduleControllerDocs.java
Labels: 🔨 Refactor

#49 [Feature] 여행 일정에 유저를 초대할 수 있는 링크를 생성 구현
  src/main/java/com/wegotoo/application/invitation/InvitationService.java
  src/main/java/com/wegotoo/application/schedule/ScheduleGroupService.java
  src/main/java/com/wegotoo/domain/invitation/Invitation.java
  src/main/java/com/wegotoo/domain/invitation/repository/InvitationRepository.java
  src/main/java/com/wegotoo/domain/schedule/repository/ScheduleGroupRepository.java
  src/main/java/com/wegotoo/exception/ErrorCode.java
Labels: ✨ Feature

#50 [Feature] 채팅 전송 기능 구현
  build.gradle
  docker-compose.dev.yml
  src/main/java/com/wegotoo/api/GlobalStompExceptionHandler.java
  src/main/java/com/wegotoo/api/chat/ChatController.java
  src/main/java/com/wegotoo/api/chat/request/ChatSendRequest.java
  src/main/java/com/wegotoo/application/chat/ChatResponse.java
  src/main/java/com/wegotoo/application/chat/ChatService.java
  src/main/java/com/wegotoo/application/chat/request/ChatSendServiceRequest.java
  src/main/java/com/wegotoo/config/EmbeddedMongoConfig.java
  src/main/java/com/wegotoo/config/MongoConfig.java
  src/main/java/com/wegotoo/config/SecurityConfig.java
  src/main/java/com/wegotoo/config/WebSocketConfig.java
  src/main/java/com/wegotoo/domain/chat/Chat.java
  src/main/java/com/wegotoo/domain/chat/repository/ChatRepository.java
  src/main/java/com/wegotoo/exception/ErrorResponse.java
  src/main/java/com/wegotoo/infra/resolver/auth/AuthMessageArgumentResolver.java
  src/main/java/com/wegotoo/infra/socket/JwtSocketAuthorizationHandler.java
  src/main/java/com/wegotoo/infra/socket/WebSocketErrorHandler.java
  src/main/resources/application-local.yml
  src/test/java/com/wegotoo/application/chat/ChatServiceTest.java
  src/test/resources/application.yml
Labels: ✨ Feature

#52 [Feature] 앱 토큰 재발급 기능 개발
  src/docs/asciidoc/api/accompany/accompany.adoc
  src/docs/asciidoc/api/auth/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wegotoo/api/auth/AuthController.java
  src/main/java/com/wegotoo/application/auth/AuthService.java
  src/main/java/com/wegotoo/config/EmbeddedMongoConfig.java
  src/main/java/com/wegotoo/config/SecurityConfig.java
  src/main/java/com/wegotoo/config/WebConfig.java
  src/main/java/com/wegotoo/infra/resolver/refresh/AppRefreshToken.java
  src/main/java/com/wegotoo/infra/resolver/refresh/AppRefreshTokenArgumentResolver.java
  src/main/java/com/wegotoo/infra/security/jwt/filter/JwtLogoutFilter.java
  src/main/java/com/wegotoo/infra/security/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/wegotoo/infra/security/redirect/RedirectResponseBuilder.java
  src/main/java/com/wegotoo/infra/security/redirect/staregy/AppRedirectStrategy.java
  src/main/java/com/wegotoo/infra/security/redirect/staregy/DefaultRedirectStrategy.java
  src/main/java/com/wegotoo/infra/security/redirect/staregy/RedirectStrategy.java
  src/main/java/com/wegotoo/infra/security/redirect/staregy/WebRedirectStrategy.java
  src/main/java/com/wegotoo/infra/security/util/ServletUtils.java
  src/main/java/com/wegotoo/infra/security/util/UriUtils.java
  src/test/java/com/wegotoo/api/ControllerTestSupport.java
  src/test/java/com/wegotoo/api/auth/AuthControllerTest.java
  src/test/java/com/wegotoo/application/auth/AuthServiceTest.java
  src/test/java/com/wegotoo/docs/RestDocsSupport.java
  src/test/java/com/wegotoo/docs/auth/AuthControllerDocs.java
  src/test/java/com/wegotoo/support/ControllerWebMvcTest.java
  src/test/java/com/wegotoo/support/config/TestWebConfig.java
  src/test/java/com/wegotoo/support/security/MockAuthUtils.java
Labels: ✨ Feature

#56 [Fix] 앱 리다이렉션 URI 오류 수정
  src/main/java/com/wegotoo/infra/security/redirect/staregy/WebRedirectStrategy.java
Labels: 🐞 BugFix

#57 [Feature] SSE를 활용하여 채팅 알림 구현
  src/docs/asciidoc/api/accompany/accompany.adoc
  src/docs/asciidoc/api/notification/notification.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wegotoo/api/notification/NotificationController.java
  src/main/java/com/wegotoo/application/chat/ChatService.java
  src/main/java/com/wegotoo/application/event/ChatMessageSentEvent.java
  src/main/java/com/wegotoo/application/event/ChatMessageSentEventListener.java
  src/main/java/com/wegotoo/application/notification/NotificationService.java
  src/main/java/com/wegotoo/config/SecurityConfig.java
  src/main/java/com/wegotoo/domain/notification/Notification.java
  src/main/java/com/wegotoo/domain/notification/repository/NotificationRepository.java
  src/main/java/com/wegotoo/domain/notification/repository/SseEmitterRepository.java
  src/main/java/com/wegotoo/exception/ErrorCode.java
  src/main/java/com/wegotoo/exception/NotificationSendException.java
  src/test/java/com/wegotoo/api/ControllerTestSupport.java
  src/test/java/com/wegotoo/application/notification/NotificationServiceTest.java
  src/test/java/com/wegotoo/docs/RestDocsSupport.java
  src/test/java/com/wegotoo/docs/notification/NotificationControllerDocs.java
  src/test/java/com/wegotoo/support/ControllerWebMvcTest.java
Labels: ✨ Feature

#59 [Feature] 여행 동행 모집 글 조회 시 필드 추가
  src/main/java/com/wegotoo/api/accompany/AccompanyController.java
  src/main/java/com/wegotoo/application/accompany/response/AccompanyFindAllResponse.java
  src/main/java/com/wegotoo/application/accompany/response/AccompanyFindOneResponse.java
  src/main/java/com/wegotoo/domain/accompany/repository/AccompanyRepositoryImpl.java
  src/main/java/com/wegotoo/domain/accompany/repository/response/AccompanyFindAllQueryEntity.java
  src/main/java/com/wegotoo/domain/accompany/repository/response/AccompanyFindOneQueryEntity.java
  src/test/java/com/wegotoo/docs/accompany/AccompanyControllerDocs.java
Labels: ✨ Feature

#60 [Feature] 채팅방 전체 조회 API 구현
  src/docs/asciidoc/api/chatroom/chatRoom.adoc
  src/main/java/com/wegotoo/api/chatroom/ChatRoomController.java
  src/main/java/com/wegotoo/application/chat/ChatService.java
  src/main/java/com/wegotoo/application/chatroom/ChatRoomService.java
  src/main/java/com/wegotoo/application/chatroom/response/ChatRoomFindAllResponse.java
  src/main/java/com/wegotoo/domain/chat/Chat.java
  src/main/java/com/wegotoo/domain/chat/repository/ChatRepository.java
  src/main/java/com/wegotoo/domain/chat/repository/ChatRepositoryCustom.java
  src/main/java/com/wegotoo/domain/chat/repository/ChatRepositoryImpl.java
  src/main/java/com/wegotoo/domain/chatroom/UserChatRoom.java
  src/main/java/com/wegotoo/domain/chatroom/UserChatRoomQueryEntity.java
  src/main/java/com/wegotoo/domain/chatroom/repository/ChatRoomIds.java
  src/main/java/com/wegotoo/domain/chatroom/repository/UserChatRoomRepository.java
  src/main/java/com/wegotoo/domain/chatroom/repository/UserChatRoomRepositoryCustom.java
  src/main/java/com/wegotoo/domain/chatroom/repository/UserChatRoomRepositoryImpl.java
  src/test/java/com/wegotoo/api/chatroom/ChatRoomControllerTest.java
  src/test/java/com/wegotoo/application/chatroom/ChatRoomServiceTest.java
  src/test/java/com/wegotoo/docs/chatroom/ChatRoomControllerDocs.java
  src/test/java/com/wegotoo/domain/chat/repository/ChatRepositoryImplTest.java
  src/test/java/com/wegotoo/domain/chatroom/repository/UserChatRoomRepositoryImplTest.java
Labels: ✨ Feature

#64 [Feature] 채팅방 단건 조회 API 구현
  src/docs/asciidoc/api/chatroom/chatRoom.adoc
  src/main/java/com/wegotoo/api/chatroom/ChatRoomController.java
  src/main/java/com/wegotoo/application/chatroom/ChatRoomService.java
  src/main/java/com/wegotoo/application/chatroom/response/ChatRoomFindAllResponse.java
  src/main/java/com/wegotoo/application/chatroom/response/ChatRoomFindOneResponse.java
  src/main/java/com/wegotoo/application/chatroom/response/ChatRoomUserResponse.java
  src/main/java/com/wegotoo/domain/chatroom/UserChatRoomQueryEntity.java
  src/main/java/com/wegotoo/domain/chatroom/repository/UserChatRoomRepository.java
  src/main/java/com/wegotoo/domain/chatroom/repository/UserChatRoomRepositoryImpl.java
  src/main/java/com/wegotoo/exception/ErrorCode.java
  src/test/java/com/wegotoo/api/chatroom/ChatRoomControllerTest.java
  src/test/java/com/wegotoo/application/chatroom/ChatRoomServiceTest.java
  src/test/java/com/wegotoo/docs/chatroom/ChatRoomControllerDocs.java
Labels: ✨ Feature
